### ISSUE TITLE
Compatibility with python 3.x

### ISSUE THREAD

**Issue by Schmetzler** [darin-costello/spheropy#1]
As I tried this package I could not use it with python 3.5 on windows. So I just added 3 lines to `Sphero.py` and now it works.
```python
# ... other imports
import sys 
if sys.version_info > (3,):
    buffer = bytes
# ...
```
basically this replaces all uses of `buffer` with `bytes`, due to buffer being unsupported in python 3.x
I don't know if there are other issues, but this worked for me (I use pybluez 0.22)

**Comment by darin-costello** [comment]
Merged in the pull request.
